name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2 

    - name: Set up Python
      uses: actions/setup-python@v2 
      with:
        python-version: '3.8'

    - name: Create Virtual Environment
      run: python -m venv venv

    - name: Activate Virtual Environment
      run: |
        source venv/bin/activate

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install pytest selenium pytest-html

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Execute Tests Chrome
      run: |
        source venv/bin/activate
        /opt/hostedtoolcache/Python/3.8.18/x64/python -m pytest testsChrome --html=reportChrome.html \
                --self-contained-html \
                --capture=sys \
                --verbose \
                --showlocals \
                --durations=0 

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4 
      if: always()
      with:
        name: TestReportsSE-ExemploChrome_html
        path: reportChrome.html

    - name: Execute Tests Edge
      run: |
        source venv/bin/activate
        /opt/hostedtoolcache/Python/3.8.18/x64/python -m pytest testsEdge --html=reportEdge.html \
                --self-contained-html \
                --capture=sys \
                --verbose \
                --showlocals \
                --durations=0 

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4 
      if: always()
      with:
        name: TestReportsSE-ExemploEdge_html
        path: reportEdge.html   